### ISSUE TITLE
Why is the number of both labeled and unlabeled 80-LABELED_ID_NUM

### ISSUE THREAD

**Issue by yang12138std** [AiEson/CrossMatch#3]
![image](https://github.com/AiEson/CrossMatch/assets/80250693/ea9b567b-cbea-40ee-8f9a-e14f8cd6a673)
![image](https://github.com/AiEson/CrossMatch/assets/80250693/a38eb505-7134-477e-9b56-a314063bd95a)

**Comment by AiEson** [comment]
This is because we need to ensure that the lengths of trainset_u and trainset_l are consistent, so that they can be merged into a `dataloader` using `zip()`. What really plays a role in data isolation is the incoming `id_path`.
Used in `trainset_l`
```python
if num is not None:
    self.image_list = self.image_list * 21
    self.image_list = self.image_list[:num]
```
to ensure that the same length as `trainset_u` is obtained.

<img width="875" alt="image" src="https://github.com/AiEson/CrossMatch/assets/32814260/94c41800-2fec-4723-ba9d-4855bba74577">
